export const serverUrl = "http://localhost:8081/";

export const ADD_TO_CART = "ADD_TO_CART";
export type ADD_TO_CART = typeof ADD_TO_CART;
export const DELETE_FROM_CART = "DELETE_FROM_CART";
export type DELETE_FROM_CART = typeof DELETE_FROM_CART;
export const QUANTITY_CHANGED = "QUANTITY_CHANGED";
export type QUANTITY_CHANGED = typeof QUANTITY_CHANGED;
export const CLEAR_CART = "CLEAR_CART";
export type CLEAR_CART = typeof CLEAR_CART;

export const FETCH_GOODS_SUCCESS = "FETCH_GOODS_SUCCESS";
export const FETCH_GOODS_FAILURE = "FETCH_GOODS_FAILURE";
export const FETCH_GOODS_REQUEST = "FETCH_GOODS_REQUEST";
export const CREATE_GOOD_SUCCESS = "CREATE_GOOD_SUCCESS";
export const CREATE_GOOD_FAILURE = "CREATE_GOOD_SUCCESS";
export const DELETE_GOOD_SUCCESS = "DELETE_GOOD_SUCCESS";
export const DELETE_GOOD_FAILURE = "DELETE_GOOD_FAILURE";
export const UPDATE_GOOD_FAILURE = "UPDATE_GOOD_FAILURE";

export const LOGIN = "LOGIN";
export const LOGOUT = "LOGOUT";
